/**
 * Day-1 interop spike: validates in one go that
 *  - noble's compressed-G1 decoding matches midnight-curves' encoding,
 *  - our Blake2b256 digest-reset transcript matches the Rust one,
 *  - scalar LE encoding and challenge sampling are right.
 *
 * Oracle: the poseidon artifacts generated by
 * `cargo run --example export_visualiser -- --check` (vk.json + trace.json,
 * whose `challenges` were captured inside the Rust prover).
 */

import { describe, expect, it } from "vitest";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { g1FromHex, g1ToHex } from "../verifier/curve";
import { Blake2b256Transcript } from "../verifier/transcript";
import { fromLEHex, hexToBytes, toLEHex } from "../verifier/field";

const ARTIFACTS = join(__dirname, "../../public/artifacts/poseidon");
const vk = JSON.parse(readFileSync(join(ARTIFACTS, "vk.json"), "utf8"));
const trace = JSON.parse(readFileSync(join(ARTIFACTS, "trace.json"), "utf8"));

describe("noble curves interop", () => {
  it("decompresses and re-serialises all vk commitments", () => {
    const points: string[] = [
      ...vk.vk.fixed_commitments,
      ...vk.vk.permutation_commitments,
      ...vk.committed_instances,
    ];
    expect(points.length).toBeGreaterThan(0);
    for (const hex of points) {
      const p = g1FromHex(hex);
      expect(g1ToHex(p)).toBe(hex);
    }
  });

  it("parses the vk transcript_repr as a canonical scalar", () => {
    const repr = fromLEHex(vk.vk.transcript_repr);
    expect(toLEHex(repr)).toBe(vk.vk.transcript_repr);
  });
});

describe("Blake2b256 transcript interop", () => {
  it("re-derives theta..y from the proof, matching the Rust prover", () => {
    const proof = hexToBytes(vk.proof);
    const t = new Blake2b256Transcript(proof);
    const cs = vk.vk.cs;

    // Step 0: vk digest.
    t.absorbScalar("vk.transcript_repr", fromLEHex(vk.vk.transcript_repr));

    // Step 0': committed instance commitments, then plain instance columns
    // (length as scalar, then values).
    for (const ci of vk.committed_instances) {
      t.absorb("committed_instance", hexToBytes(ci));
    }
    for (const column of vk.instances) {
      t.absorbScalar("instance.len", BigInt(column.length));
      for (const v of column) t.absorbScalar("instance", fromLEHex(v));
    }

    // Step 1: advice commitments.
    for (let i = 0; i < cs.num_advice_columns; i++) t.readPoint(`advice_${i}`);

    // Step 2: theta.
    expect(toLEHex(t.squeezeChallenge("theta"))).toBe(trace.challenges.theta);

    // Step 3: one multiplicities commitment per lookup argument.
    for (let i = 0; i < cs.lookups.length; i++) t.readPoint(`logup_m_${i}`);

    // Step 4: beta, gamma.
    expect(toLEHex(t.squeezeChallenge("beta"))).toBe(trace.challenges.beta);
    expect(toLEHex(t.squeezeChallenge("gamma"))).toBe(trace.challenges.gamma);

    // Step 5: permutation grand-product commitments, one per chunk of
    // (degree - 2) permutation columns.
    const chunkLen = cs.degree - 2;
    const numChunks = Math.ceil(cs.permutation_columns.length / chunkLen);
    for (let c = 0; c < numChunks; c++) t.readPoint(`perm_z_${c}`);

    // Step 6: per lookup: helpers (num_chunks) then aggregator.
    for (const lookup of cs.lookups) {
      for (let j = 0; j < lookup.num_chunks; j++) t.readPoint("logup_h");
      t.readPoint("logup_agg");
    }

    // Step 7: trash challenge; step 8: trash commitments.
    expect(toLEHex(t.squeezeChallenge("trash"))).toBe(trace.challenges.trash);
    for (let g = 0; g < cs.trash.length; g++) t.readPoint(`trash_${g}`);

    // Step 9: y.
    expect(toLEHex(t.squeezeChallenge("y"))).toBe(trace.challenges.y);
  });
});
